apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity: 
    storage: 200Mi
  storageClassName: slow
  persistentVolumeReclaimPolicy: Recycle 
  local:
    path: /home/cloud_user/kubernetes/volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
