apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: slow
#  volumeName: pv-1
  selector:
    matchExpressions:
      - {key: pv, operator: Exists}
