apiVersion: v1
kind: Pod
metadata:
  name: pvpod-2
spec:
  containers:
  - name: busybox 
    image: busybox 
    command: ['sh', '-c', 'echo hello >> /var/test/test.txt']
    volumeMounts:
    - name: pvc-2
      mountPath: /var/test/
  volumes:
  - name: pvc-2
    persistentVolumeClaim:
      claimName: pvc-2
