apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'for i in 5; do echo hello >> /var/test/test.txt"; sleep 5; done;']
    volumeMounts:
    - name: vol-1
      mountPath: /var/test
  volumes:
  - name: vol-1
    hostPath: /home/cloud_user/kubernetes/volumes/volume

