apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-svc-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-svc
  template:
    metadata:
      labels:
        app: deployment-svc
     spec:
        containers:
        - name: nginx
          image: nginx
          ports:
          - containerPorts: 80
