apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: beebox-mobile
rules:
- apiGroup: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
 
