apiVersion: v1
metadata:
  name: build-robot-pod
kind: Pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - while true; do echo hello world; sleep 30; done
  serviceAccountName: build-robot-serviceaccount
