apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-robot-role-binding
subjects:
  - kind: ServiceAccount
    name: build-robot
    apiGroup: ""
roleRef:
  kind: Role
  name: build-robot-role
  apiGroup: rbac.authorization.k8s.io
