apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: beebox-mobile
  name: pod-reader-rolebinding
subjects:
- kind: User
  name: dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
