apiVersion: v1
metadata:
  name: g1pd
kind: Pod
spec:
  containers:
  - name: alpine 
    image: alpine
    command: ["echo", "Hello"]
    env:
      - name: G1
        valueFrom:
          configMapKeyRef:
            name: g1cm
            key: g1
    volumeMounts:
      - name: g1pd-vol
        mountPath: "/config"
  volumes:
    - name: g1pd-vol
      configMap:
        name: g1cm
        items:
          - key: g3
            path: g3
