apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
data:
  SPECIAL_LEVEL: Very
  SPECIAL_TYPE: Charm

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  special.how: very
 
