apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: label-1
  template:
    metadata:
      labels:
        app: label-1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

