apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  template:
    spec:
      containers:
        - name: busybox1
          image: busybox
          command: ['sh', '-c', 'for i in 1 2 3 4 5; do echo hello world; sleep 30; done']
        - name: pi
          image: perl
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4

      
