apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  serviceName: headless-service
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80

