apiVersion: v1
kind: Pod
metadata:
  name: pvpod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while true; do echo "hello" >> /var/output/test.txt; sleep 10; done']
    volumeMounts:
    - name: pvc1
      mountPath: /var/output
  volumes:
  - name: pvc1
    persistentVolumeClaim:
      claimName: pvc1
