apiVersion: v1
kind: DaemonSet
metadata:
  name: myDaemonSet
spec:
  selector:
    matchLabels:
      app: daemonset
  replicas: 3
  template:
    metadata:
      labels:
        app: daemonset
    spec:
      containers:
      - name: nginx
      - image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpression:
              - key: app
                operator: in
                values:
                - node 
