apiVersion: v1
kind: Pod
metadata:
  name: secret-read-pod
spec:
  containers:
  - name: busybox
    image: busybox
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret: 
      secretName: my-secret

